name: My Workflow

on:
  pull_request:
    types:
      - "labeled"
      - "unlabeled"
      - "synchronize"

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check if triggered by self
        id: check_if_self_triggered
        run: echo "::set-output name=triggered_by_self::$(test ${{ github.actor }} == 'github-actions[bot]' && echo true || echo false)"
        shell: bash

      - name: My step
        if: steps.check_if_self_triggered.outputs.triggered_by_self == 'false'
        run: |
          # Perform some action here that should only be done if the workflow is not triggered by itself
